### PR TITLE
rcar-gen2: Add gudev dependency to gst-plugins-good

### PR DESCRIPTION
**Pull request by zeenix**
Without this set, GDP builds fail:

https://at.projects.genivi.org/jira/browse/GDP-561

### CODE REVIEW

**Comment by zeenix** [comment]
I haven't tested if this fixes the build cause I can't reproduce the issue locally.

**Comment by zeenix** [comment]
I tried to reproduce again with both tmp and sstate-cache cleaned before the build and I still wasn't able to reproduce locally. We really need to get this fixed ASAP so please let me know if you want me to add the fix in a bbappend in m-g-d layer for now?

**Comment by slawr** [comment]
@zeenix: hi, from my side I will switch to looking at this from the YBSP perspective once I have completed the GDP Gen 3 pull request. Currently rebasing and testing as requested in the PR. Hope to complete today.

**Comment by zeenix** [comment]
@slawr Thanks so much! Much appreciated!

**Review by slawr — COMMENTED** [review]
I don't think this will work as it is a runtime dependency not a build time dependency. You need RDEPENDS. I don't think you need to update. I'll take a look.

**Comment by zeenix** [comment]
@slawr I'm sorry but I think you've been misinformed:

gstreamer1.0-plugins-good/1.2.3-r0/git/sys/v4l2/gstv4l2object.c:#include <gudev/gudev.h>

GStreamer plugins themselves are loaded dynamically but they themselves don't do any dynamic loading.

**Comment by zeenix** [comment]
And yes, it's very likely to work since the recipe needs the library but doesn't declared the dependency.

**Comment by zeenix** [comment]
Dropping this in favour of commit 4758a558bb3badd7108b04b8c43a8a3fbe61b958 .

**Pull request closed without merging**
